---
- name: Add Peppermint Server to LibreNMS
  hosts: peppermint-server
  become: yes
  tasks:
    - name: Ensure SNMP is installed
      apt:
        name: snmpd
        state: present

    - name: Configure SNMP
      copy:
        content: |
          agentAddress udp:161
          rocommunity public
          sysLocation Peppermint Server
          sysContact admin@example.com
        dest: /etc/snmp/snmpd.conf
        owner: root
        group: root
        mode: '0644'

    - name: Restart SNMP service
      service:
        name: snmpd
        state: restarted

    - name: Check if device exists in LibreNMS
      uri:
        url: "http://10.10.10.131/api/v0/devices/10.10.10.130"
        method: GET
        headers:
          X-Auth-Token: "YOUR_API_KEY_HERE"       # ADD YOUR API KEY HERE
        status_code: 200
      register: device_check
      failed_when: device_check.status != 200 and device_check.status != 404

    - name: Add device to LibreNMS
      uri:
        url: "http://10.10.10.131/api/v0/devices"
        method: POST
        body_format: json
        headers:
          X-Auth-Token: "e72641335829c7b5befeb6f5c10d9dc9"
        body:
          hostname: "10.10.10.130"
          version: "v2c"
          community: "public"
        status_code: [200, 201]
      when: device_check.status == 404

  post_tasks:
    - name: Print success message
      debug:
        msg: "Peppermint Server (10.10.10.130) successfully added to LibreNMS."
      when: device_check.status == 404

    - name: Print message if device already exists
      debug:
        msg: "Peppermint Server (10.10.10.130) already exists in LibreNMS."
      when: device_check.status == 200
